import { Project, Service, Skill, Stat, Testimonial, SiteConfig } from './types';

export const DEFAULT_PROJECTS: Project[] = [
  {
    id: "1",
    titleAr: "منصة تعليمية تفاعلية - EduSphere",
    titleEn: "EduSphere Interactive Learning Platform",
    descriptionAr: "نظام إدارة تعليمي متكامل (LMS) يدعم المسارات الذكية، التقييم التلقائي، ولوحات بيانات تفاعلية للمؤسسات الأكاديمية.",
    descriptionEn: "Enterprise-grade LMS with AI-powered adaptive learning paths, automated assessments, and real-time analytics dashboards for academic institutions.",
    contentAr: "تم تصميم EduSphere كنظام متكامل يجمع بين سهولة الاستخدام للمتعلمين والأدوات الرقابية للمعلمين. يدعم لوحات البيانات الديناميكية لتقدم الطلاب، والتقييم الذكي المدعوم بالذكاء الاصطناعي، وتخصيص الواجهات البصرية حسب الفئات العمرية مع تطبيق تقنية الـ Gamification لزيادة التفاعل بنسبة تجاوزت 40%.",
    contentEn: "EduSphere is a comprehensive enterprise LMS combining extreme usability for students with rich grading tools for instructors. Features responsive progress grids, AI-powered learning recommendations, automated quizzes, and visual themes custom-built to boost active session times by 40%.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "أنظمة تعليمية",
    categoryEn: "EdTech Systems",
    link: "https://example.com/project-1",
    date: "2025-11",
    sortOrder: 1,
    productType: "system",
    technologies: ["React", "Node.js", "PostgreSQL", "TensorFlow", "Redis", "WebSocket"],
    featuresAr: ["مسارات تعلم ذكية مدعومة بالـ AI", "تقييم تلقائي فوري مع تحليلات", "لوحات بيانات تفاعلية للمعلمين", "نظام Gamification للمكافآت والتحديات", "تكامل مع Zoom و Google Classroom", "دعم كامل لمعايير SCORM"],
    featuresEn: ["AI-powered adaptive learning paths", "Instant automated assessments with analytics", "Real-time instructor dashboards", "Gamification engine with rewards system", "Zoom & Google Classroom integration", "Full SCORM standard compliance"],
    status: "live",
    metrics: { users: "12K+", rating: 4.9, downloads: "5K+", uptime: "99.9%" },
    gallery: [
      "https://images.unsplash.com/photo-1501504905252-473c47e087f8?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=800&auto=format&fit=crop"
    ],
    isFeatured: true,
    accentColor: "#6366f1"
  },
  {
    id: "2",
    titleAr: "تطبيق إدارة المهام الذكي - TaskFlow",
    titleEn: "TaskFlow Smart Task Management",
    descriptionAr: "تطبيق متكامل لإدارة المشاريع والمهام مع ذكاء اصطناعي لتوزيع المهام تلقائياً وتتبع الأداء في الوقت الفعلي.",
    descriptionEn: "Next-gen project management app with AI task delegation, real-time performance tracking, and intelligent workflow automation.",
    contentAr: "يتميز TaskFlow بواجهة Bento Grid عصرية تتيح التحكم الكامل بالسحب والإفلات. يدعم لوحات التحكم الديناميكية، التنبيهات الذكية، الإحصائيات المتطورة، وتصميم واجهات ناعم ومريح للעין. يستخدم خوارزميات الذكاء الاصطناعي لتوزيع المهام بناءً على أداء الفريق ومهاراتهم.",
    contentEn: "TaskFlow features a beautiful Bento Grid UI with full drag-and-drop control. Includes dynamic boards, smart notifications, advanced metrics, and eye-safe aesthetics. Uses AI algorithms to intelligently distribute tasks based on team performance and skill sets.",
    image: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "تطبيقات إنتاجية",
    categoryEn: "Productivity Apps",
    link: "https://example.com/project-2",
    date: "2026-02",
    sortOrder: 2,
    productType: "app",
    technologies: ["React Native", "TypeScript", "Firebase", "OpenAI API", "Stripe"],
    featuresAr: ["توزيع ذكي للمهام بالذكاء الاصطناعي", "لوحات Kanban تفاعلية مع سحب وإفلات", "تقارير أداء الفريق الأسبوعية", "تكامل مع Slack و Microsoft Teams", "وضع التركيز مع مؤقت Pomodoro", "إشعارات ذكية متعددة القنوات"],
    featuresEn: ["AI-powered intelligent task distribution", "Interactive Kanban boards with drag-and-drop", "Weekly team performance reports", "Slack & Microsoft Teams integration", "Focus mode with Pomodoro timer", "Multi-channel smart notifications"],
    status: "live",
    metrics: { users: "28K+", rating: 4.8, downloads: "15K+" },
    gallery: [
      "https://images.unsplash.com/photo-1611224923853-80b023f02d71?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1531403009284-440f080d1e12?q=80&w=800&auto=format&fit=crop"
    ],
    isFeatured: false,
    accentColor: "#8b5cf6"
  },
  {
    id: "3",
    titleAr: "متجر إلكتروني عصري - LuxeStore",
    titleEn: "LuxeStore Premium E-commerce Platform",
    descriptionAr: "منصة تجارة إلكترونية متكاملة مع تجربة تسوق ثلاثية الأبعاد، نظام دفع ذكي، ولوحة تحكم تجارية شاملة.",
    descriptionEn: "Full-featured e-commerce platform with 3D product visualization, smart checkout engine, and comprehensive merchant dashboard.",
    contentAr: "LuxeStore يدمج بين التجارة الإلكترونية التقليدية والمعارض التفاعلية ثلاثية الأبعاد. يتميز بـ Micro-animations سلسة، وتأثيرات Glassmorphism للمنتجات، وتحسين مذهل للأداء وصل إلى 98% في PageSpeed. يتضمن نظام إدارة مخزون ذكي وتحليلات سلوك المشتري بالذكاء الاصطناعي.",
    contentEn: "LuxeStore fuses traditional e-commerce with interactive 3D product showcases. Features smooth micro-animations, glassmorphism product cards, and achieved 98% PageSpeed score. Includes smart inventory management and AI-powered buyer behavior analytics.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "أنظمة تجارة إلكترونية",
    categoryEn: "E-commerce Systems",
    link: "https://example.com/project-3",
    date: "2026-04",
    sortOrder: 3,
    productType: "platform",
    technologies: ["Next.js", "Stripe", "Sanity CMS", "Three.js", "Tailwind", "Vercel"],
    featuresAr: ["عرض منتجات ثلاثي الأبعاد تفاعلي", "نظام دفع ذكي متعدد الخيارات", "لوحة تحكم تجارية شاملة", "تحليلات سلوك المشتري بالـ AI", "إدارة مخزون ذكية مع تنبيهات", "دعم RTL كامل للعربية"],
    featuresEn: ["Interactive 3D product visualization", "Smart multi-option checkout engine", "Comprehensive merchant dashboard", "AI-powered buyer behavior analytics", "Smart inventory management with alerts", "Full RTL Arabic language support"],
    status: "live",
    metrics: { users: "45K+", rating: 4.7, downloads: "22K+", uptime: "99.8%" },
    gallery: [
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=800&auto=format&fit=crop"
    ],
    isFeatured: true,
    accentColor: "#f59e0b"
  },
  {
    id: "4",
    titleAr: "نظام الهوية الرقمية - BrandForge",
    titleEn: "BrandForge Digital Identity System",
    descriptionAr: "نظام متكامل لإدارة الهوية البصرية الرقمية يشمل مولد الشعارات بالذكاء الاصطناعي، دليل العلامة التجارية، وأدوات تصميم تلقائية.",
    descriptionEn: "Complete digital identity management system with AI logo generator, brand guidelines engine, and automated design tools.",
    contentAr: "BrandForge يوفر نظاماً شاملاً لإدارة الهوية البصرية من منصة واحدة. يتضمن مولداً للشعارات بالذكاء الاصطناعي، نظام إنشاء دليل العلامة التجارية تلقائياً، وأدوات تصميم المطبوعات والسوشيال ميديا. يدعم تصدير جميع الملفات بصيغ متعددة عالية الدقة.",
    contentEn: "BrandForge provides a comprehensive visual identity management system from a single platform. Includes an AI logo generator, automated brand guideline creation, and design tools for print and social media. Supports exporting all assets in multiple high-resolution formats.",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "أنظمة تصميم",
    categoryEn: "Design Systems",
    link: "https://example.com/project-4",
    date: "2025-08",
    sortOrder: 4,
    productType: "system",
    technologies: ["React", "D3.js", "Canvas API", "OpenAI DALL-E", "Figma Plugin", "SVG.js"],
    featuresAr: ["مولد شعارات ذكي بالـ AI", "دليل علامة تجارية تلقائي", "أدوات تصميم المطبوعات", "مولد منشورات السوشيال ميديا", "تصدير بصيغ متعددة عالية الدقة", "تكامل مع Figma و Adobe"],
    featuresEn: ["AI-powered smart logo generator", "Automated brand guideline creation", "Print design tools", "Social media post generator", "Multi-format high-res export", "Figma & Adobe integration"],
    status: "live",
    metrics: { users: "8K+", rating: 4.6, downloads: "3K+" },
    gallery: [
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=800&auto=format&fit=crop"
    ],
    isFeatured: false,
    accentColor: "#ec4899"
  },
  {
    id: "5",
    titleAr: "تطبيق الصحة واللياقة - VitalSync",
    titleEn: "VitalSync Health & Fitness App",
    descriptionAr: "تطبيق صحي شامل لتتبع اللياقة البدنية، التغذية، والصحة النفسية مع مدرب ذكي اصطناعي ومخططات تقدم تفاعلية.",
    descriptionEn: "Comprehensive health app tracking fitness, nutrition, and mental wellness with an AI personal trainer and interactive progress charts.",
    contentAr: "يركز VitalSync على تجميع البيانات الصحية المعقدة وعرضها في شكل بصري مبسط ومبهج. يستخدم نبرات الألوان المفعمة بالحيوية والرسوم البيانية التوضيحية الديناميكية. يتضمن مدرباً ذكياً يقترح تمارين مخصصة بناءً على تقدم المستخدم وأهدافه الصحية.",
    contentEn: "VitalSync centers on making complex health data inviting and readable. Uses energetic color palettes, custom circular dials, and gamified progress cards. Features an AI trainer suggesting personalized exercises based on user progress and health goals.",
    image: "https://images.unsplash.com/photo-1510519138101-570d1dca3d66?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "تطبيقات صحة",
    categoryEn: "Health & Fitness Apps",
    link: "https://example.com/project-5",
    date: "2025-05",
    sortOrder: 5,
    productType: "app",
    technologies: ["React Native", "HealthKit", "Google Fit", "Firebase ML", "Chart.js", "Node.js"],
    featuresAr: ["مدرب ذكي اصطناعي للتمارين", "تتبع النوم والنشاط اليومي", "مخططات تغذية مخصصة", "تحديات اجتماعية مع الأصدقاء", "تكامل مع Apple Watch و Fitbit", "تقارير طبية شهرية شاملة"],
    featuresEn: ["AI personal fitness trainer", "Sleep and daily activity tracking", "Custom nutrition meal plans", "Social challenges with friends", "Apple Watch & Fitbit integration", "Comprehensive monthly health reports"],
    status: "live",
    metrics: { users: "35K+", rating: 4.9, downloads: "20K+" },
    gallery: [
      "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?q=80&w=800&auto=format&fit=crop"
    ],
    isFeatured: false,
    accentColor: "#10b981"
  },
  {
    id: "6",
    titleAr: "منصة Web3 للعملات المشفرة - CryptoVerse",
    titleEn: "CryptoVerse Web3 Ecosystem",
    descriptionAr: "منصة متكاملة لتداول العملات المشفرة، إدارة المحافظ الرقمية، وتحليل السوق بالذكاء الاصطناعي مع واجهة Cyberpunk عصرية.",
    descriptionEn: "Full Web3 ecosystem for crypto trading, digital wallet management, and AI market analysis with a futuristic Cyberpunk interface.",
    contentAr: "CryptoVerse يدمج بين تكنولوجيا البلوك تشين وتفرد التصميم الرقمي. يتميز بمخططات بيانية فورية للأسعار، ودعم كامل لمحافظ التشفير المتعددة، ومظهر نيلي برتقالي نابض مع تأثيرات مالتيميديا جذابة. يستخدم خوارزميات التحليل الفني بالذكاء الاصطناعي لتوقعات السوق.",
    contentEn: "CryptoVerse fuses blockchain technology with unique digital design. Features live price tickers, multi-wallet support, and neon blue-orange aesthetics with engaging multimedia effects. Uses AI technical analysis algorithms for market predictions.",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "أنظمة مالية رقمية",
    categoryEn: "FinTech / Web3 Systems",
    link: "https://example.com/project-6",
    date: "2026-01",
    sortOrder: 6,
    productType: "platform",
    technologies: ["React", "Solidity", "Web3.js", "Ethers.js", "D3.js", "Node.js", "GraphQL"],
    featuresAr: ["تداول لحظي مع رسوم بيانية تفاعلية", "محافظ رقمية متعددة متزامنة", "تحليل فني ذكي بالـ AI", "صفقات تلقائية (Trading Bots)", "تكامل مع MetaMask و WalletConnect", "أمان متعدد الطبقات (2FA + Biometric)"],
    featuresEn: ["Real-time trading with interactive charts", "Multi-wallet synchronized management", "AI-powered technical analysis", "Automated trading bots", "MetaMask & WalletConnect integration", "Multi-layer security (2FA + Biometric)"],
    status: "beta",
    metrics: { users: "18K+", rating: 4.5, downloads: "9K+" },
    gallery: [
      "https://images.unsplash.com/photo-1642790106117-e829e14a795f?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1621761191319-c6fb62004040?q=80&w=800&auto=format&fit=crop"
    ],
    isFeatured: false,
    accentColor: "#06b6d4"
  },
  {
    id: "7",
    titleAr: "نظام تشخيص الصور الطبية - MediScan AI",
    titleEn: "MediScan AI Medical Diagnostics",
    descriptionAr: "نظام تشخيص طبي مدعوم بالذكاء الاصطناعي لتحليل الأشعة السينية والرنين المغناطيسي بدقة فائقة مع تقارير تلقائية.",
    descriptionEn: "AI-powered medical diagnostic system for MRI & X-Ray analysis with ultra-high accuracy and automated reporting.",
    contentAr: "MediScan AI مصمم للأطباء والاستشاريين لتسهيل قراءة الصور الطبية بدقة تصل إلى 99.2%. يتميز بواجهة مستخدم غاية في البساطة مع ميزات ذكية مثل التلوين الحراري لمناطق الإصابة، المقارنة التاريخية للصور، والتقارير الطبية التلقائية المعدة بالذكاء الاصطناعي التوليدي مع الامتثال الكامل لمعايير HIPAA.",
    contentEn: "MediScan AI is built for radiologists and consultants to enhance MRI/X-ray reading with 99.2% accuracy. Features an ultra-clean interface with smart capabilities like thermal highlighting for injury zones, historical scan comparisons, and automated diagnostic reports drafted using Generative AI under full HIPAA compliance.",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "أنظمة طبية ذكية",
    categoryEn: "HealthTech AI Systems",
    link: "https://example.com/project-7",
    date: "2026-03",
    sortOrder: 7,
    productType: "system",
    technologies: ["Python", "TensorFlow", "React", "DICOM", "FastAPI", "AWS S3", "PostgreSQL"],
    featuresAr: ["تشخيص بالذكاء الاصطناعي بدقة 99.2%", "تلوين حراري لمناطق الإصابة", "مقارنة تاريخية للصور الطبية", "تقارير تلقائية بالـ Generative AI", "امتثال كامل لمعايير HIPAA", "تكامل مع أنظمة المستشفيات (PACS)"],
    featuresEn: ["AI diagnosis with 99.2% accuracy", "Thermal highlighting for injury zones", "Historical scan comparison timeline", "Generative AI automated reports", "Full HIPAA compliance", "Hospital systems integration (PACS)"],
    status: "live",
    metrics: { users: "2.5K+", rating: 4.9, uptime: "99.99%" },
    gallery: [
      "https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?q=80&w=800&auto=format&fit=crop"
    ],
    isFeatured: true,
    accentColor: "#ef4444"
  },
  {
    id: "8",
    titleAr: "منصة إدارة الثروات - ApexFinance",
    titleEn: "ApexFinance Wealth Management Portal",
    descriptionAr: "منصة استثمارية ذكية لإدارة المحافظ المالية، تتبع الأسهم والعملات المشفرة مع لوحات تحكم تفاعلية وتحليلات متقدمة.",
    descriptionEn: "Smart investment platform for portfolio management, stock & crypto tracking with interactive dashboards and advanced analytics.",
    contentAr: "ApexFinance يجمع بين الرسوم البيانية التفاعلية الفورية وتحليلات المخاطر الذكية. تم استخدام واجهات بصرية غنية بتأثيرات الزجاج الشفاف (Glassmorphism)، مع تباينات لونية رائعة باستخدام D3.js لرسوم بيانية مبسطة تساعد المستثمرين في اتخاذ قراراتهم بثقة.",
    contentEn: "ApexFinance integrates live interactive charts with smart risk analytics. Uses rich glassmorphism visual interfaces with stunning color contrasts, featuring D3.js-powered simplified charts helping investors make confident decisions.",
    image: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "أنظمة مالية",
    categoryEn: "FinTech Solutions",
    link: "https://example.com/project-8",
    date: "2026-05",
    sortOrder: 8,
    productType: "system",
    technologies: ["React", "D3.js", "Python", "FastAPI", "WebSocket", "Redis", "PostgreSQL"],
    featuresAr: ["لوحات بيانات تفاعلية فورية", "تحليل مخاطر ذكي بالـ AI", "تتبع محافظ متعددة الأصول", "إشعارات تنبيهات الأسعار", "تقارير استثمارية شهرية", "تكامل مع Bloomberg و Yahoo Finance"],
    featuresEn: ["Real-time interactive dashboards", "AI-powered risk analysis", "Multi-asset portfolio tracking", "Price alert notifications", "Monthly investment reports", "Bloomberg & Yahoo Finance integration"],
    status: "live",
    metrics: { users: "15K+", rating: 4.7, uptime: "99.95%" },
    gallery: [
      "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=800&auto=format&fit=crop"
    ],
    isFeatured: false,
    accentColor: "#f97316"
  },
  {
    id: "9",
    titleAr: "تطبيق السياحة الفاخرة - AeroElite",
    titleEn: "AeroElite Private Travel Concierge",
    descriptionAr: "تطبيق حجز رحلات فاخرة للطائرات الخاصة واليخوت مع خدمة كونسيرج ذكية وتصميم واجهة فخمة.",
    descriptionEn: "Premium flight and yacht charter booking app with AI concierge service and luxurious interface design.",
    contentAr: "AeroElite يركز على الفخامة والبساطة المطلقة لتناسب ذائقة كبار الشخصيات. يضم نظام حجز ذكي، تخطيط مباشر لمسارات الرحلات على الخريطة التفاعلية، خدمة محادثة فورية للحجوزات الخاصة، ومؤثرات حركية فائقة السلاسة تشعرك بالرفاهية.",
    contentEn: "AeroElite emphasizes absolute simplicity and luxury for ultra-high-net-worth clients. Includes smart booking, dynamic map routing, instant VIP chat support, and fluid transitions creating an atmosphere of ultimate hospitality.",
    image: "https://images.unsplash.com/photo-1540962351504-03099e0a754b?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "تطبيقات سياحة",
    categoryEn: "Travel & Luxury Apps",
    link: "https://example.com/project-9",
    date: "2026-01",
    sortOrder: 9,
    productType: "app",
    technologies: ["React Native", "MapBox", "Node.js", "Stripe", "Twilio", "MongoDB"],
    featuresAr: ["حجز طائرات خاصة ويخوت فاخرة", "خريطة تفاعلية لتخطيط المسارات", "خدمة كونسيرج ذكية 24/7", "واجهة فاخرة بتأثيرات حركية سلسة", "نظام دفع آمن متعدد العملات", "برنامج ولاء VIP للمستخدمين"],
    featuresEn: ["Private jet and luxury yacht booking", "Interactive map route planning", "24/7 AI concierge service", "Luxury UI with fluid animations", "Secure multi-currency payment", "VIP loyalty program"],
    status: "live",
    metrics: { users: "5K+", rating: 4.8, downloads: "2K+" },
    gallery: [
      "https://images.unsplash.com/photo-1436491865332-7a61a109db05?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1540962351504-03099e0a754b?q=80&w=800&auto=format&fit=crop"
    ],
    isFeatured: false,
    accentColor: "#d946ef"
  },
  {
    id: "10",
    titleAr: "معرض الفنون الرقمية ثلاثي الأبعاد - VividMuse",
    titleEn: "VividMuse 3D Virtual Art Gallery",
    descriptionAr: "معرض فني افتراضي غامر ثلاثي الأبعاد يتيح للزوار التجوال داخل صالة عرض فنية واستعراض وشراء اللوحات الرقمية.",
    descriptionEn: "Immersive 3D virtual museum allowing visitors to explore galleries, view artwork in detail, and purchase verified digital masterpieces.",
    contentAr: "VividMuse يجمع بين الفنون الكلاسيكية والتفاعل الرقمي الحديث باستخدام WebGL و Three.js. توفر تجربة تجول افتراضية بزاوية 360 درجة، وإضاءة تفاعلية وظلال واقعية، مع إمكانية المزايدة على الأعمال الفنية بأمان عبر البلوك تشين.",
    contentEn: "VividMuse fuses classic museology with WebGL and Three.js mechanics. Offers 360-degree free roaming, dynamic gallery lighting shaders, high-DPI zoom interactions, and secure blockchain-based auction bidding for artworks.",
    image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "تجارب ويب ثلاثية الأبعاد",
    categoryEn: "3D Web Experiences",
    link: "https://example.com/project-10",
    date: "2026-04",
    sortOrder: 10,
    productType: "platform",
    technologies: ["Three.js", "WebGL", "React", "Blender", "Solidity", "IPFS", "GSAP"],
    featuresAr: ["تجوال افتراضي 360 درجة", "إضاءة تفاعلية واقعية", "تكبير عالي الدقة للوحات", "مزاد إلكتروني آمن بالبلوك تشين", "تعليق صوتي من الفنانين", "معرض مخصص لكل فنان"],
    featuresEn: ["360-degree virtual roaming", "Realistic interactive lighting", "High-DPI artwork zoom", "Blockchain-secured art auctions", "Artist audio commentary", "Custom gallery per artist"],
    status: "beta",
    metrics: { users: "7K+", rating: 4.8, downloads: "3K+" },
    gallery: [
      "https://images.unsplash.com/photo-1561214115-f2f134cc4912?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?q=80&w=800&auto=format&fit=crop"
    ],
    isFeatured: false,
    accentColor: "#a855f7"
  }
];

export const DEFAULT_SERVICES: Service[] = [
  {
    id: "s1",
    titleAr: "تصميم واجهات المستخدم (UI Design)",
    titleEn: "UI Design",
    descriptionAr: "تصميم واجهات فريدة، جذابة وسهلة الاستخدام بأسلوب بصري حديث يعكس رقي علامتك التجارية ويعزز انخراط عملائك.",
    descriptionEn: "Crafting beautiful, modern visual interfaces that maximize brand character, elevate digital charm, and hook your potential audience.",
    icon: "Layout"
  },
  {
    id: "s2",
    titleAr: "تجربة المستخدم المتطورة (UX Design)",
    titleEn: "UX Design & Research",
    descriptionAr: "دراسة سلوكيات المستخدمين وتطوير هيكلية وايرفريم ممتازة واختبار سيناريوهات الاستخدام لضمان أقصى درجات السهولة والفاعلية.",
    descriptionEn: "Researching client behaviors, formulating high-tier wireframes, and testing interactions to achieve organic, highly-logical user flows.",
    icon: "Layers"
  },
  {
    id: "s3",
    titleAr: "تطوير الواجهات الأمامية (Front-end)",
    titleEn: "Front-end Web Development",
    descriptionAr: "تحويل التصاميم الخيالية إلى أكواد برمجية حقيقية، نظيفة، فائقة السرعة ومتجاوبة تماماً مع مختلف الشاشات والأجهزة بفعالية.",
    descriptionEn: "Converting complex responsive sketches into production-ready, clean, lightweight code that scales natively on any active screen sizes.",
    icon: "Code"
  },
  {
    id: "s4",
    titleAr: "الاستشارات والرؤى الرقمية",
    titleEn: "Strategic Digital Consulting",
    descriptionAr: "تقديم تحليلات معمقة لمشروعك الرقمي قبل البدء فيه أو لتحديثه، لضمان تبني أحدث صيحات التصميم والتطوير العالمية بنجاح.",
    descriptionEn: "Providing complete strategic advice and modern usability audits to elevate your digital presence and optimize development budgets.",
    icon: "Sparkles"
  },
  {
    id: "s5",
    titleAr: "التصميم الجرافيكي الإبداعي",
    titleEn: "Creative Graphic Design",
    descriptionAr: "تصميم الهويات البصرية، الشعارات، والمطبوعات الاحترافية بلمسة فنية مميزة تعزز حضور علامتك التجارية في السوق.",
    descriptionEn: "Designing corporate visual identities, masterfully crafted logos, and marketing materials that capture your audience.",
    icon: "Palette"
  },
  {
    id: "s6",
    titleAr: "منشورات شبكات التواصل الاجتماعي",
    titleEn: "Social Media Graphic Content",
    descriptionAr: "تصميم منشورات جذابة ومحتوى تفاعلي مبتكر لمنصات التواصل الاجتماعي المختلفة بما يضمن تفاعل الجمهور ونمو المتابعين.",
    descriptionEn: "Formulating high-engagement visual post templates, story grids, and custom digital marketing content for social networks.",
    icon: "Share2"
  }
];

export const DEFAULT_SKILLS: Skill[] = [
  { id: "sk1", nameAr: "تصميم واجهات الويب والـ UI", nameEn: "Web & UI Design", percentage: 95, categoryAr: "التصميم", categoryEn: "Design" },
  { id: "sk2", nameAr: "أبحاث تجربة المستخدم والـ UX", nameEn: "UX Research & Prototyping", percentage: 90, categoryAr: "التصميم", categoryEn: "Design" },
  { id: "sk3", nameAr: "تطوير الواجهات (React / Vite)", nameEn: "Front-end (React / Vite)", percentage: 88, categoryAr: "التطوير", categoryEn: "Development" },
  { id: "sk4", nameAr: "تنسيق وتخطيط المكونات Tailwind", nameEn: "Tailwind CSS Layouts", percentage: 96, categoryAr: "التطوير", categoryEn: "Development" },
  { id: "sk5", nameAr: "متحركات الحركة والـ Framer / Motion", nameEn: "Micro-animations & Motion", percentage: 85, categoryAr: "التصميم", categoryEn: "Design" },
  { id: "sk6", nameAr: "تصميم وإخراج الهويات التجارية", nameEn: "Brand Architecture & Identity", percentage: 80, categoryAr: "العلامات التجارية", categoryEn: "Branding" }
];

export const DEFAULT_STATS: Stat[] = [
  { id: "st1", value: "+50", labelAr: "مشروع مكتمل", labelEn: "Completed Projects" },
  { id: "st2", value: "+5", labelAr: "سنوات الخبرة الإبداعية", labelEn: "Years of Experience" },
  { id: "st3", value: "100%", labelAr: "رضا العملاء والشغف", labelEn: "Client Satisfaction" }
];

export const DEFAULT_TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    nameAr: "عبد الله الغامدي",
    nameEn: "Abdallah Al-Ghamdi",
    roleAr: "الرئيس التنفيذي، تكنو-ريد",
    roleEn: "CEO, TechnoRed",
    commentAr: "عمل رائع ومتقن للغاية من مالك! استطاع ترجمة رؤيتنا بدقة وصنع لنا موقعاً بهوية ومظهر فني ترك انطباعاً مذهلاً لدى جميع شركائنا وعملائنا.",
    commentEn: "An absolutely stunning piece of work by Malek! He captured our complex concepts and refined them into an interactive work of art. Our clients are mind-blown.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&auto=format&fit=crop"
  },
  {
    id: "t2",
    nameAr: "سارة جونسون",
    nameEn: "Sarah Johnson",
    roleAr: "مديرة التسويق، هيلثي للياقة",
    roleEn: "Marketing Manager, Healthy Vitality",
    commentAr: "احترافية فائقة في تصميم واجهة تطبيق الجوال. سرعة في التنفيذ واقتراحات ممتازة طوال فترة التطوير رفعت جودة مخرجات المشروع.",
    commentEn: "Outstanding professionalism in designing our mobile UI layouts. Malek operates fast, responds quickly, and brought invaluable UX feedback to the table.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&auto=format&fit=crop"
  }
];

export const DEFAULT_CONFIG: SiteConfig = {
  aboutTextAr: "أنا مالك أحمد (مالك لوجيك)، مصمم ومطور واجهات ويب محترف مقيم في العالم الرقمي. لأكثر من 5 سنوات، كرست شغفي لتحويل الأفكار الإبداعية إلى واجهات تفاعلية مذهلة وتجارب مستخدم لا تُنسى. أجمع بين اللمسة الفنية الأنيقة والمهارة التقنية العالية لتقديم حلول متكاملة تضمن تفوق عملائي.",
  aboutTextEn: "I am Malek, professional UI/UX Designer & Frontend Developer, known digitally as Malek Logic. For over 5 years, I've committed my energy to transforming challenging concepts into pixel-perfect interfaces and immersive interactive systems. I bridge visual elegance with modern code standards to yield products that standout.",
  heroTextAr: "أصنع تجارب رقمية إبداعية تروي قصتك",
  heroTextEn: "Designing Digital Experiences That Tell Your Story",
  heroSubAr: "دمج احترافي بين الإبداع البصري القائم على الـ Glassmorphism والتطوير البرمجي الفائق لصنع واجهات رقمية مذهلة وقابلة للتوسع.",
  heroSubEn: "Fusing beautiful Glassmorphism design and micro-animations with ultra-fast frontend engineering to craft interfaces that inspire and scale.",
  profileImg: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop",
  logoImg: "",
  heroBgImg: "",
  nameAr: "المهندس مالك لوجيك",
  nameEn: "Malek Ahmed",
  professionAr: "مصمم ومطور تفاعلي",
  professionEn: "UI/UX & Web Dev Artist",
  logoTextAr: "مالك لوجيك",
  logoTextEn: "MALEK LOGIC",
  fontFamily: "thmanyah-sans",
  customFontFamily: "",
  customFontUrl: "",
  accentColor: "#1C99ED",
  socialFacebook: "https://facebook.com/malekart",
  socialTwitter: "https://twitter.com/malekart",
  socialLinkedin: "https://linkedin.com/in/malekart",
  socialGithub: "https://github.com/malekart",
  socialInstagram: "https://instagram.com/malekart",
  socialLinks: [
    { id: 'soc-1', platform: 'GitHub', url: 'https://github.com/malekart' },
    { id: 'soc-2', platform: 'LinkedIn', url: 'https://linkedin.com/in/malekart' },
    { id: 'soc-3', platform: 'Twitter/X', url: 'https://twitter.com/malekart' },
    { id: 'soc-4', platform: 'Instagram', url: 'https://instagram.com/malekart' }
  ],
  stat1Value: "+50",
  stat1LabelAr: "مشروع مكتمل",
  stat1LabelEn: "Completed Projects",
  stat2Value: "+5",
  stat2LabelAr: "سنوات الخبرة الإبداعية",
  stat2LabelEn: "Years of Experience",
  stat3Value: "100%",
  stat3LabelAr: "رضا العملاء والشغف",
  stat3LabelEn: "Client Satisfaction",
  aiCustomPromptAr: "نظام مستشار التخطيط الذكي - نشط وجاهز للتحليل الفوري باحترافية كاملة.",
  aiCustomPromptEn: "Intelligent Project Advisor - Active, responsive, and ready for modern product layouts.",
  resumePhone: "+966 50 000 0000",
  resumeEmail: "malikalwesabi@gmail.com",
  resumeLocation: "الرياض، المملكة العربية السعودية / Riyadh, KSA",
  resumeSummaryAr: "مصمم ومطور تفاعلي شغوف، ذو خبرة تفوق الخمس سنوات في تحويل الأفكار الإبداعية إلى منتجات رقمية فريدة تدمج بين جمال التصميم وقوة الأداء التقني واستهداف تجارب مستخدم حرة.",
  resumeSummaryEn: "Highly passionate UI/UX Designer & Web Developer with 5+ years of active experience bringing creative visual ideas to life through robust frontend architectures and sleek design specs.",
  resumeExperienceAr: "• مصمم واجهات رائد - استوديو مالك لوجيك الرياض (2023 - الآن): قيادة تصميم واجهات المستخدم لأكثر من 30 تطبيقاً رقمياً استثنائياً وتصميم أنظمة تصميم موحدة.\n• مطور واجهات ويب - منصات إبداعية رقمية (2021 - 2023): بناء وتطوير منصات ويب متجاوبة وتفاعلية لعملاء في الشرق الأوسط باستخدام React وTailwind.\n• مصمم مستقل ومستشار للشركات الناشئة والمصانع الرقمية (2019 - 2021)",
  resumeExperienceEn: "• Lead UI/UX Designer - Malek Logic Studio Riyadh (2023 - Present): Leading design files for 30+ innovative software solutions and configuring highly interactive design systems.\n• Frontend Engineer - Creative Digital Platforms (2021 - 2023): Developing lightweight responsive web apps using modern React, Tailwind, and high-DPI assets.\n• Freelance Interaction Designer & Startup Consultant (2019 - 2021)",
  resumeEducationAr: "• بكالوريوس في علوم الحاسوب وتقنيات الويب\n• شهادة متخصصة معتمدة في هندسة تجربة المستخدم وتفاعل الإنسان مع الحاسوب",
  resumeEducationEn: "• Bachelor's Degree in Computer Science & Web Technologies\n• Advanced Professional Certification in UX Architecture & Human-Computer Interaction"
};

export const TRANSLATIONS = {
  ar: {
    navHome: "الرئيسية",
    navAbout: "من أنا",
    navServices: "الخدمات",
    navPortfolio: "ملف الأعمال",
    navMatchmaker: "مستشار الذكاء الاصطناعي",
    navContact: "تواصل معي",
    navAdmin: "لوحة التحكم",
    navAdminExit: "خروج من الإدارة",
    
    heroTitlePrefix: "مرحباً في عالم",
    heroTitleName: "مالك لوجيك | Malek Logic",
    heroAccentTitle: "مصمم ومطور واجهات ويب",
    heroCtaWork: "شاهد أعمالي",
    heroCtaContact: "تواصل مباشر",
    
    statsSecTitle: "نجاح بالأرقام",
    
    aboutSecTitle: "من أكون؟",
    aboutSubtitle: "قصص نجاح نرويها بالإبداع والتفوق التقني",
    aboutYears: "سنوات خبرة متواصلة",
    aboutSkillsTitle: "ترسانة المهارات الإبداعية",
    downloadCv: "تحميل السيرة الذاتية",
    
    servicesSecTitle: "الخدمات الإبداعية",
    servicesSubtitle: "كيف يمكنني مساعدة مشروعك على الريادة الرقمية؟",
    
    portfolioSecTitle: "معرض المنتجات",
    portfolioSubtitle: "استكشف مجموعتنا من الأنظمة والتطبيقات والمنصات الرقمية المتكاملة المصممة بأعلى معايير الجودة والأداء",
    filterAll: "سائر الأعمال",
    viewProject: "تفاصيل العمل",
    visitLive: "زيارت الموقع",
    projectCategory: "التصنيف:",
    projectDate: "التاريخ:",
    closeBtn: "إغلاق",
    
    aiSecTitle: "مستشار التخطيط الذكي (AI)",
    aiSubtitle: "اكتب فكرة مشروعك، وسيقوم الذكاء الاصطناعي بتحليلها واقتراح كيفية تنفيذه مع عرض المشاريع المشابهة لك من أعمال مالك",
    aiPlaceholder: "مثال: أريد إنشاء تطبيق لإدارة المطاعم بواجهات فاخرة وتصميم داكن وحركات أنيقة...",
    aiBudgetText: "مستوى الميزانية التقريبي:",
    aiBudgetLow: "محدودة (أقل من $2000)",
    aiBudgetMid: "متوسطة ($2000 - $5000)",
    aiBudgetHigh: "متقدمة (أكثر من $5000)",
    aiSubmitBtn: "تحليل وتوصيف المشروع بالذكاء الاصطناعي",
    aiAnalyzing: "جاري اتصال ذكي بالنموذج وجدولة التقرير...",
    aiError: "حدث خطأ أثناء إجراء التحليل الذكي. يرجى المحاولة لاحقاً.",
    aiMatchesHeader: "المشاريع الملهمة المشابهة من أعمالي:",
    aiApproachHeader: "خطة مالك المقترحة لتنفيذ مشروعك:",
    aiNoInput: "الرجاء كتابة فكرة مشروعك للحصول على الاستشارة الفورية.",
    
    contactSecTitle: "لنصنع عملاً استثنائياً معاً",
    contactSubtitle: "هل لديك فكرة مشروع أو ترغب باستشارة مجانية؟ بادر بالتواصل وسأرد عليك خلال 24 ساعة.",
    contactName: "الاسم الكريم",
    contactEmail: "بريدك الإلكتروني",
    contactSubject: "موضوع الرسالة",
    contactSubjectUi: "طلب تصميم واجهات UI/UX",
    contactSubjectDev: "تطوير موقع أو تطبيق ويب",
    contactSubjectBranding: "بناء هوية بصرية بالكامل",
    contactSubjectConsult: "استشارة رقمية وتقنية",
    contactSubjectOther: "أمر آخر",
    contactMessage: "تفاصيل رسالتك أو فكرتك",
    contactSubmitBtn: "إرسال رسالتك الآن",
    contactSending: "جاري إرسال الرسالة السلكية...",
    contactSuccess: "شكراً لتواصلك الفاخر! تم استلام رسالتك بنجاح وسأقوم بالتواصل معك في أقرب فرصة.",
    contactError: "حدث خطأ ما، يرجى ملء الحقول المطلوبة والتأكد من بريدك الإلكتروني.",
    socialLinksTitle: "تابعنا على وسائل التواصل الاجتماعي",
    
    adminLoginTitle: "بوابة التحكم الآمنة",
    adminPasswordLabel: "كلمة مرور المدير",
    adminLoginBtn: "دخول آمن",
    adminIncorrect: "كلمة المرور غير صحيحة، يرجى المحاولة مجدداً.",
    adminWelcome: "مرحباً مالك! لوحة إدارة المحتوى الاحترافية (CMS)",
    adminTabProjects: "إدارة المشاريع",
    adminTabServices: "إدارة الخدمات",
    adminTabContent: "تعديل النصوص",
    adminTabMessages: "رسائل العملاء",
    
    adminAddProject: "إضافة مشروع جديد",
    adminEditProject: "تعديل المشروع",
    adminDeleteConfirm: "هل أنت متأكد من حذف هذا المشروع؟",
    adminSave: "حفظ التغييرات",
    adminCancel: "إلغاء الإجراء",
    
    adminProjTitleAr: "العنوان بالعربية",
    adminProjTitleEn: "العنوان بالإنجليزية",
    adminProjDescAr: "الوصف المختصر بالعربية",
    adminProjDescEn: "الوصف المختصر بالإنجليزية",
    adminProjContAr: "التفاصيل الطويلة بالعربية",
    adminProjContEn: "التفاصيل الطويلة بالإنجليزية",
    adminProjImage: "رابط صورة المعاينة (URL)",
    adminProjCatAr: "التصنيف بالعربية",
    adminProjCatEn: "التصنيف بالإنجليزية",
    adminProjLink: "رابط مباشر للموقع (اختياري)",
    adminProjDate: "تاريخ المشروع (مثال: 2026-06)",
    adminProjOrder: "الرقم الترتيبي للظهور",
    
    adminServTitleAr: "اسم الخدمة بالعربية",
    adminServTitleEn: "اسم الخدمة بالإنجليزية",
    adminServDescAr: "الوصف بالعربية",
    adminServDescEn: "الوصف بالإنجليزية",
    adminServIcon: "اسم الأيقونة من Lucide",
    
    adminContHeroAr: "العنوان الرئيسي المفتتح بالعربية",
    adminContHeroEn: "العنوان الرئيسي المفتتح بالإنجليزية",
    adminContHeroSubAr: "الوصف الفرعي بالبطل بالعربية",
    adminContHeroSubEn: "الوصف الفرعي بالبطل بالإنجليزية",
    adminContAboutAr: "نبذة عني بالعربية",
    adminContAboutEn: "نبذة عني بالإنجليزية",
    adminContProfile: "رابط الصورة الشخصية",
    adminContSaveSuccess: "تم حفظ نصوص الموقع بنجاح!",
    
    adminNoMessages: "لا توجد رسائل عملاء واردة حتى الآن.",
    adminMsgFrom: "المرسل:",
    adminMsgSubject: "الموضوع:",
    adminMsgDate: "تاريخ الاستلام:",
    adminDeleteMsg: "حذف الرسالة",
    
    footerRights: "جميع الحقوق محفوظة. تم تصميمه بكل شغف وإبداع بواسطة مالك لوجيك © 2026",
    footerRightsEn: "All Rights Reserved. Handcrafted with passion & code by Malek Logic © 2026"
  },
  en: {
    navHome: "Home",
    navAbout: "About Me",
    navServices: "Services",
    navPortfolio: "Portfolio",
    navMatchmaker: "AI Consultation",
    navContact: "Contact",
    navAdmin: "CMS Panel",
    navAdminExit: "Exit CMS",
    
    heroTitlePrefix: "Welcome to the world of",
    heroTitleName: "Malek Logic",
    heroAccentTitle: "UI/UX Designer & Web Developer",
    heroCtaWork: "View Portfolio",
    heroCtaContact: "Get in Touch",
    
    statsSecTitle: "Success in Numbers",
    
    aboutSecTitle: "Who Is Malek?",
    aboutSubtitle: "Fusing Design Aesthetics with Pure Engineering Craft",
    aboutYears: "Years Active Experience",
    aboutSkillsTitle: "Creative Skill Armory",
    downloadCv: "Download Resume",
    
    servicesSecTitle: "My Services",
    servicesSubtitle: "Elevating your brand visual and digital business capabilities",
    
    portfolioSecTitle: "Selected Projects",
    portfolioSubtitle: "A curated workspace exhibiting stellar frontend apps and interface systems",
    filterAll: "All Works",
    viewProject: "Project Details",
    visitLive: "Visit Website",
    projectCategory: "Category:",
    projectDate: "Date:",
    closeBtn: "Close",
    
    aiSecTitle: "Intelligent Project Advisor (AI)",
    aiSubtitle: "Submit your core business concept. Our custom AI will suggest execution guidelines, modern technical stacks, and map it directly to related works of Malek.",
    aiPlaceholder: "Example: I want a sleek dashboard for real-estate listing that uses futuristic dark UI, smooth glass transitions, and works blazing fast...",
    aiBudgetText: "Estimated Project Budget:",
    aiBudgetLow: "Entry-Level (Under $2000)",
    aiBudgetMid: "Growth ($2000 - $5000)",
    aiBudgetHigh: "Enterprise (Above $5000)",
    aiSubmitBtn: "Analyze Project with Gemini Intelligence",
    aiAnalyzing: "Contacting server-side model nodes & compiling index...",
    aiError: "An issue occurred connecting to the assistant nodes. Please inspect your config or try again.",
    aiMatchesHeader: "Similar Inspiring Works from My Portfolio:",
    aiApproachHeader: "Malek's Recommended Strategy & Stack:",
    aiNoInput: "Please write down your product idea to start AI consultation mapping.",
    
    contactSecTitle: "Let's Craft Something Stellar",
    contactSubtitle: "Possess an inspiring idea or need structured technical consultation? Message me and let's get rolling immediately.",
    contactName: "Your Full Name",
    contactEmail: "Email Address",
    contactSubject: "Message Subject",
    contactSubjectUi: "UI/UX Interface Design",
    contactSubjectDev: "Web Development Request",
    contactSubjectBranding: "Brand Identity Architecture",
    contactSubjectConsult: "Digital Audit & Consulting",
    contactSubjectOther: "Other Topic",
    contactMessage: "Tell me about your vision/project context",
    contactSubmitBtn: "Deploy Message Into Orbit",
    contactSending: "Broadcasting message across arrays...",
    contactSuccess: "Message acquired successfully! I will reach out to you within the next 24 hours.",
    contactError: "Please fulfill all required fields and confirm your email format.",
    socialLinksTitle: "Follow Us on Social Media",
    
    adminLoginTitle: "Protected Administrator Tunnel",
    adminPasswordLabel: "Vault Password",
    adminLoginBtn: "Establish Session",
    adminIncorrect: "Incorrect credentials. Secure lockout parameters active.",
    adminWelcome: "Welcome back, Malek. Digital Content Management Suite",
    adminTabProjects: "Projects Catalog",
    adminTabServices: "Services List",
    adminTabContent: "Main Content Sheets",
    adminTabMessages: "Inbox Submissions",
    
    adminAddProject: "Add Project Node",
    adminEditProject: "Update Project Node",
    adminDeleteConfirm: "Are you absolutely state-resolved to delete this project?",
    adminSave: "Commit Updates",
    adminCancel: "Suspend Workflow",
    
    adminProjTitleAr: "Title (Arabic)",
    adminProjTitleEn: "Title (English)",
    adminProjDescAr: "Brief Description (Arabic)",
    adminProjDescEn: "Brief Description (English)",
    adminProjContAr: "Deep Overview Description (Arabic)",
    adminProjContEn: "Deep Overview Description (English)",
    adminProjImage: "Showcase Image Path/URL",
    adminProjCatAr: "Category (Arabic)",
    adminProjCatEn: "Category (English)",
    adminProjLink: "Demo Address Link (Optional)",
    adminProjDate: "Date Node (Format: YYYY-MM)",
    adminProjOrder: "Index Placement Weight",
    
    adminServTitleAr: "Service Label (Arabic)",
    adminServTitleEn: "Service Label (English)",
    adminServDescAr: "Brief Description (Arabic)",
    adminServDescEn: "Brief Description (English)",
    adminServIcon: "Lucide Icon Key Name",
    
    adminContHeroAr: "Main Hero Broadcaster (Arabic)",
    adminContHeroEn: "Main Hero Broadcaster (English)",
    adminContHeroSubAr: "Hero Paragraph Support (Arabic)",
    adminContHeroSubEn: "Hero Paragraph Support (English)",
    adminContAboutAr: "About Malek Block (Arabic)",
    adminContAboutEn: "About Malek Block (English)",
    adminContProfile: "Portrait Image URL Link",
    adminContSaveSuccess: "Content segments saved into local memory successfully!",
    
    adminNoMessages: "No customer queries populated so far.",
    adminMsgFrom: "Originator:",
    adminMsgSubject: "Topic:",
    adminMsgDate: "Composed At:",
    adminDeleteMsg: "Purge Node",
    
    footerRights: "All Rights Reserved. Handcrafted with passion & code by Malek Logic © 2026",
    footerRightsEn: "All Rights Reserved. Handcrafted with passion & code by Malek Logic © 2026"
  }
};
