import { Project, Service, Skill, Stat, Testimonial, SiteConfig } from './types';

export const DEFAULT_PROJECTS: Project[] = [
  {
    id: "1",
    titleAr: "منصة تعليمية تفاعلية",
    titleEn: "Interactive Learning Platform",
    descriptionAr: "تجربة تعلم رقمية تفاعلية قائمة على اللعب والرسوم البيانية المخصصة ومسارات التعلم الذكية للمؤسسات الأكاديمية.",
    descriptionEn: "Gamified, highly-interactive e-learning system with custom analytics, tailored progress meters, and smart curriculums.",
    contentAr: "تم تصميم المنصة كحل متكامل للجمع بين سهولة الاستخدام للمتعلمين والأدوات الرقابية للمعلمين. تدعم لوحات البيانات لتقدم الطلاب والتقييم الذكي وتخصيص الواجهات البصرية حسب الفئات العمرية مع تطبيق تقنية الـ Gamification لزيادة التفاعل بنسبة تجاوزت 40%.",
    contentEn: "Designed as an end-to-end framework combining extreme usability for students with rich grading tools for instructors. Features responsive progress grids, AI learning recommendations, automated quizzes, and visual themes custom-built to boost active session times by 40%.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "UI/UX",
    categoryEn: "UI/UX",
    link: "https://example.com/project-1",
    date: "2025-11",
    sortOrder: 1
  },
  {
    id: "2",
    titleAr: "تطبيق إدارة المهام الذكي",
    titleEn: "Smart Task Management App",
    descriptionAr: "تطبيق متكامل لتنظيم المشاريع وإدارة الوقت مع تكامل الذكاء الاصطناعي وجدولة تلقائية للمهام في الوقت الفعلي.",
    descriptionEn: "Next-gen task management workflow with smart prioritization, interactive calendars, and streamlined team cooperation panels.",
    contentAr: "واجهة معاصرة بأسلوب الـ Bento Grid تتيح التحكم الكامل للمستخدم بالسحب والإفلات. يدعم التطبيق لوحات التحكم الديناميكية، التنبيهات الذكية، الإحصائيات المتطورة، وتصميم واجهات ناعم ومريح للعين يقلل من تشتت المستخدمين.",
    contentEn: "Features a beautiful Bento Grid UI designed to bring instant order to your projects. Includes interactive drag-and-drop boards, focus modes, team chat integrations, metrics visualizers, and an eye-safe aesthetic built for heavy professional workflows.",
    image: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "تطوير ويب",
    categoryEn: "Web Development",
    link: "https://example.com/project-2",
    date: "2026-02",
    sortOrder: 2
  },
  {
    id: "3",
    titleAr: "متجر إالكتروني عصري",
    titleEn: "Creative E-commerce Website",
    descriptionAr: "تجربة تسوق ثلاثية الأبعاد بأسلوب فريد وتصميم زجاجي عصري وسرعة استجابة فائقة للدفع السريع.",
    descriptionEn: "Highly immersive virtual showcase with intuitive shopping cart modules, customized layout transitions, and fluid checkout guides.",
    contentAr: "مشروع رائد يدمج بين التجارة الإلكترونية التقليدية والمعارض التفاعلية. يتميز بـ Micro-animations سلسة، وتأثيرات Glassmorphism للمنتجات، وتحسين مذهل للأداء وصل إلى 98% في السرعة لتعزيز معدلات التحويل.",
    contentEn: "A visionary digital store fusing fluid animations and ambient blur glass cards with raw technical performance. Achieved an outstanding 98% PageSpeed ranking to ensure optimal conversation rates and ultra-responsive buying cycles.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "UI/UX + تطوير",
    categoryEn: "UI/UX + Development",
    link: "https://example.com/project-3",
    date: "2026-04",
    sortOrder: 3
  },
  {
    id: "4",
    titleAr: "الهوية الرقمية لشركة تكنو-ريد",
    titleEn: "TechnoRed Digital Identity",
    descriptionAr: "تصميم هوية بصرية متميزة تشمل الشعارات، المطبوعات، الدليل الفني للعلامة التجارية والموقع التعريفي التفاعلي.",
    descriptionEn: "Complete branding package including logos, stationery, color palettes, typography specs, and an engaging web launch site.",
    contentAr: "تطوير هوية بصرية قوية تعتمد على البساطة والخطوط الحادة لتعزز الحضور التكنولوجي للعلامة. شمل العمل تصميم الموقع بأسلوب جريء ثنائي الأبعاد وتأثيرات تفاعلية تتوافق مع فلسفة التصميم الحديثة.",
    contentEn: "Developing a bold visual trademark for a cutting-edge robotics firm. Centered on futuristic letterforms, minimalist spacing, dynamic geometric patterns, and a clean style system that translates elegantly from vector print assets onto a vibrant landing portal.",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "علامات تجارية",
    categoryEn: "Branding",
    link: "https://example.com/project-4",
    date: "2025-08",
    sortOrder: 4
  },
  {
    id: "5",
    titleAr: "تطبيق هيلثي للياقة البدنية",
    titleEn: "Healthy Vitality Wellness App",
    descriptionAr: "واجهة مستخدم متكاملة لتتبع الصحة والتمارين الرياضية مخصصة للتحفيز الذاتي والأنشطة الاجتماعية المشتركة.",
    descriptionEn: "Immersive visual interfaces for tracking daily health metrics, diet details, training schedules, and friendly group goals.",
    contentAr: "يركز التصميم على تجميع البيانات المعقدة وعرضها في شكل بصري مبسط ومبهج. تم استخدام نبرات الألوان المفعمة بالحيوية والرسوم البيانية التوضيحية الديناميكية والصفحات الدقيقة المصممة لتأكيد التقدم اليومي للمستخدم.",
    contentEn: "Centered on making complex biometrics, calories, and goals inviting and readable. Uses soft energetic color pulses, custom circular dials, and gamified progress cards to keep modern users engaged with their fitness program on a daily basis.",
    image: "https://images.unsplash.com/photo-1510519138101-570d1dca3d66?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "UI/UX",
    categoryEn: "UI/UX",
    link: "https://example.com/project-5",
    date: "2025-05",
    sortOrder: 5
  },
  {
    id: "6",
    titleAr: "منصة ويب ثري الإبداعية",
    titleEn: "Web3 Creative Hub",
    descriptionAr: "بناء منصة تفاعلية متجاوبة للعملات الرقمية والأصول المشفرة مع مخططات تفاعلية ثلاثية الأبعاد بأسلوب الـ Cyberpunk.",
    descriptionEn: "Brutalism-inspired Web3 ecosystem showcasing live exchange indexes, dynamic canvas art, and futuristic glass design elements.",
    contentAr: "دمج بين تكنولوجيا البلوك تشين وتفرد التصميم الرقمي. يتميز بمخططات بيانية فورية للأسعار، ودعم كامل لمحافظ التشفير، ومظهر نيلي برتقالي نابض مصمم مع تأثيرات مالتيميديا جذابة تضمن انخراطاً فريداً للزوار.",
    contentEn: "Fuses crypto utility sheets with cutting-edge visual layouts. Powered by live canvas tickers, crypto wallet connectors, responsive glass frames, and neon accent lines. Created to capture the fast-paced essence of decentralization.",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "تطوير ويب",
    categoryEn: "Web Development",
    link: "https://example.com/project-6",
    date: "2026-01",
    sortOrder: 6
  },
  {
    id: "7",
    titleAr: "منصة ذكاء اصطناعي لتشخيص الصور الطبية",
    titleEn: "AI Medical Image Diagnostics",
    descriptionAr: "نظام رؤية حاسوبية متكامل لتشخيص الأشعة السينية والرنين المغناطيسي بدقة فائقة بالتعاون مع كبرى المستشفيات.",
    descriptionEn: "Deep learning computer vision system for real-time MRI & X-Ray analysis, designed with top-tier healthcare standards.",
    contentAr: "منصة ويب متكاملة مصممة للأطباء والاستشاريين لتسهيل قراءة الصور الطبية بدقة تصل إلى 99.2%. يتميز المشروع بواجهة مستخدم غاية في البساطة مع ميزات ذكية مثل التلوين الحراري لمناطق الإصابة، المقارنة التاريخية للصور، والتقارير الطبية التلقائية المعدة بالذكاء الاصطناعي التوليدي مع الامتثال الكامل لمعايير HIPAA.",
    contentEn: "A comprehensive web workstation built for radiologists, enhancing MRI/X-ray reading efficiency with 99.2% accuracy. Features high-contrast interactive layout panels, real-time heatmaps for abnormality detection, historic scan timeline sliders, and automated diagnostic reports drafted using Generative AI under strict HIPAA compliance.",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "ذكاء اصطناعي",
    categoryEn: "AI + Development",
    link: "https://example.com/project-7",
    date: "2026-03",
    sortOrder: 7
  },
  {
    id: "8",
    titleAr: "البنك الرقمي السحابي لإدارة الثروات",
    titleEn: "Apex Wealth Management Portal",
    descriptionAr: "منصة استثمارية ذكية تتيح إدارة المحافظ المتقدمة، تتبع الأسهم والعملات المشفرة مع لوحة تحكم زجاجية دافئة.",
    descriptionEn: "Next-generation wealth management engine combining advanced portfolio tracking, stock diagnostics, and elegant dark mode tables.",
    contentAr: "تصميم وتطوير نظام مالي متكامل يجمع بين الرسوم البيانية التفاعلية الفورية وتحليلات المخاطر الذكية. تم استخدام واجهات بصرية غنية بتأثيرات الزجاج الشفاف (Glassmorphism)، مع تباينات لونية رائعة، ورسوم بيانية مبسطة لمساعدة المستثمرين في اتخاذ قراراتهم الاستثمارية بثقة وسهولة.",
    contentEn: "Designed and engineered an elite financial web platform integrating live market data streams and responsive risk-mitigation modules. Styled with high-contrast warm charcoal and glowing amber accents, featuring bespoke interactive chart sheets utilizing D3.js for clean, elegant, and action-oriented financial clarity.",
    image: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "أنظمة مالية",
    categoryEn: "FinTech Solutions",
    link: "https://example.com/project-8",
    date: "2026-05",
    sortOrder: 8
  },
  {
    id: "9",
    titleAr: "منصة الطيران والسياحة الفاخرة",
    titleEn: "AeroElite Private Travel Concierge",
    descriptionAr: "تجربة حجز وتصميم رحلات سياحية خاصة وطائرات خاصة حول العالم مع خدمة كونسيرج تفاعلية مخصصة للنخبة.",
    descriptionEn: "Premium flight and yacht charter platform with real-time route plotting, private hospitality guides, and luxury design layout.",
    contentAr: "يركز هذا المشروع على الفخامة والبساطة المطلقة لتناسب ذائقة كبار الشخصيات. يضم نظام حجز ذكي، تخطيط مباشر لمسارات الرحلات على الخريطة التفاعلية، خدمة محادثة فورية للحجوزات الخاصة، ومؤثرات حركية فائقة السلاسة تشعرك بالرفاهية منذ اللحظة الأولى لتصفح الموقع.",
    contentEn: "A visionary booking system designed for ultra-high-net-worth clients, emphasizing absolute simplicity and luxurious editorial spacing. Includes dynamic map routing interfaces, private luxury yacht/flight customizers, instant VIP support integrations, and fluid page transitions creating a flawless atmosphere of hospitality.",
    image: "https://images.unsplash.com/photo-1540962351504-03099e0a754b?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "تطبيقات جوال",
    categoryEn: "Mobile + Web UX",
    link: "https://example.com/project-9",
    date: "2026-01",
    sortOrder: 9
  },
  {
    id: "10",
    titleAr: "المعرض الافتراضي للفنون الرقمية ثلاثية الأبعاد",
    titleEn: "VividMuse 3D Virtual Art Space",
    descriptionAr: "مساحة فنية غامرة تتيح للزوار التجول داخل صالة عرض فنية ثلاثية الأبعاد واستعراض اللوحات الرقمية بدقة عالية.",
    descriptionEn: "Immersive 3D museum environment allowing users to explore virtual galleries and purchase verified digital masterpieces.",
    contentAr: "منصة رائدة تجمع بين الفنون الكلاسيكية والتفاعل الرقمي الحديث باستخدام WebGL وThree.js. توفر تجربة تجول افتراضية حرة بزاوية 360 درجة، وتأثيرات إضاءة تفاعلية وظلال واقعية، مع إمكانية التفاعل مع اللوحات الفنية وعرض معلومات الفنان والمزايدة على الأعمال الفنية بأمان وسهولة.",
    contentEn: "A groundbreaking artistic landscape fusing classic museology with WebGL and Three.js mechanics. Offers responsive 360-degree free roaming cameras, dynamic gallery lighting shaders, high-DPI zoom interactions on artworks, artist commentary audio, and automated smart auction bidding boards.",
    image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1200&auto=format&fit=crop",
    categoryAr: "ثلاثي الأبعاد",
    categoryEn: "3D Web Experiences",
    link: "https://example.com/project-10",
    date: "2026-04",
    sortOrder: 10
  }
];

export const DEFAULT_SERVICES: Service[] = [
  {
    id: "s1",
    titleAr: "تصميم واجهات المستخدم (UI Design)",
    titleEn: "UI Design",
    descriptionAr: "تصميم واجهات فريدة، جذابة وسهلة الاستخدام بأسلوب بصري حديث يعكس رقي علامتك التجارية ويعزز انخراط عملائك.",
    descriptionEn: "Crafting beautiful, modern visual interfaces that maximize brand character, elevate digital charm, and hook your potential audience.",
    icon: "Layout"
  },
  {
    id: "s2",
    titleAr: "تجربة المستخدم المتطورة (UX Design)",
    titleEn: "UX Design & Research",
    descriptionAr: "دراسة سلوكيات المستخدمين وتطوير هيكلية وايرفريم ممتازة واختبار سيناريوهات الاستخدام لضمان أقصى درجات السهولة والفاعلية.",
    descriptionEn: "Researching client behaviors, formulating high-tier wireframes, and testing interactions to achieve organic, highly-logical user flows.",
    icon: "Layers"
  },
  {
    id: "s3",
    titleAr: "تطوير الواجهات الأمامية (Front-end)",
    titleEn: "Front-end Web Development",
    descriptionAr: "تحويل التصاميم الخيالية إلى أكواد برمجية حقيقية، نظيفة، فائقة السرعة ومتجاوبة تماماً مع مختلف الشاشات والأجهزة بفعالية.",
    descriptionEn: "Converting complex responsive sketches into production-ready, clean, lightweight code that scales natively on any active screen sizes.",
    icon: "Code"
  },
  {
    id: "s4",
    titleAr: "الاستشارات والرؤى الرقمية",
    titleEn: "Strategic Digital Consulting",
    descriptionAr: "تقديم تحليلات معمقة لمشروعك الرقمي قبل البدء فيه أو لتحديثه، لضمان تبني أحدث صيحات التصميم والتطوير العالمية بنجاح.",
    descriptionEn: "Providing complete strategic advice and modern usability audits to elevate your digital presence and optimize development budgets.",
    icon: "Sparkles"
  },
  {
    id: "s5",
    titleAr: "التصميم الجرافيكي الإبداعي",
    titleEn: "Creative Graphic Design",
    descriptionAr: "تصميم الهويات البصرية، الشعارات، والمطبوعات الاحترافية بلمسة فنية مميزة تعزز حضور علامتك التجارية في السوق.",
    descriptionEn: "Designing corporate visual identities, masterfully crafted logos, and marketing materials that capture your audience.",
    icon: "Palette"
  },
  {
    id: "s6",
    titleAr: "منشورات شبكات التواصل الاجتماعي",
    titleEn: "Social Media Graphic Content",
    descriptionAr: "تصميم منشورات جذابة ومحتوى تفاعلي مبتكر لمنصات التواصل الاجتماعي المختلفة بما يضمن تفاعل الجمهور ونمو المتابعين.",
    descriptionEn: "Formulating high-engagement visual post templates, story grids, and custom digital marketing content for social networks.",
    icon: "Share2"
  }
];

export const DEFAULT_SKILLS: Skill[] = [
  { id: "sk1", nameAr: "تصميم واجهات الويب والـ UI", nameEn: "Web & UI Design", percentage: 95, categoryAr: "التصميم", categoryEn: "Design" },
  { id: "sk2", nameAr: "أبحاث تجربة المستخدم والـ UX", nameEn: "UX Research & Prototyping", percentage: 90, categoryAr: "التصميم", categoryEn: "Design" },
  { id: "sk3", nameAr: "تطوير الواجهات (React / Vite)", nameEn: "Front-end (React / Vite)", percentage: 88, categoryAr: "التطوير", categoryEn: "Development" },
  { id: "sk4", nameAr: "تنسيق وتخطيط المكونات Tailwind", nameEn: "Tailwind CSS Layouts", percentage: 96, categoryAr: "التطوير", categoryEn: "Development" },
  { id: "sk5", nameAr: "متحركات الحركة والـ Framer / Motion", nameEn: "Micro-animations & Motion", percentage: 85, categoryAr: "التصميم", categoryEn: "Design" },
  { id: "sk6", nameAr: "تصميم وإخراج الهويات التجارية", nameEn: "Brand Architecture & Identity", percentage: 80, categoryAr: "العلامات التجارية", categoryEn: "Branding" }
];

export const DEFAULT_STATS: Stat[] = [
  { id: "st1", value: "+50", labelAr: "مشروع مكتمل", labelEn: "Completed Projects" },
  { id: "st2", value: "+5", labelAr: "سنوات الخبرة الإبداعية", labelEn: "Years of Experience" },
  { id: "st3", value: "100%", labelAr: "رضا العملاء والشغف", labelEn: "Client Satisfaction" }
];

export const DEFAULT_TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    nameAr: "عبد الله الغامدي",
    nameEn: "Abdallah Al-Ghamdi",
    roleAr: "الرئيس التنفيذي، تكنو-ريد",
    roleEn: "CEO, TechnoRed",
    commentAr: "عمل رائع ومتقن للغاية من مالك! استطاع ترجمة رؤيتنا بدقة وصنع لنا موقعاً بهوية ومظهر فني ترك انطباعاً مذهلاً لدى جميع شركائنا وعملائنا.",
    commentEn: "An absolutely stunning piece of work by Malek! He captured our complex concepts and refined them into an interactive work of art. Our clients are mind-blown.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&auto=format&fit=crop"
  },
  {
    id: "t2",
    nameAr: "سارة جونسون",
    nameEn: "Sarah Johnson",
    roleAr: "مديرة التسويق، هيلثي للياقة",
    roleEn: "Marketing Manager, Healthy Vitality",
    commentAr: "احترافية فائقة في تصميم واجهة تطبيق الجوال. سرعة في التنفيذ واقتراحات ممتازة طوال فترة التطوير رفعت جودة مخرجات المشروع.",
    commentEn: "Outstanding professionalism in designing our mobile UI layouts. Malek operates fast, responds quickly, and brought invaluable UX feedback to the table.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&auto=format&fit=crop"
  }
];

export const DEFAULT_CONFIG: SiteConfig = {
  aboutTextAr: "أنا مالك أحمد (مالك لوجيك)، مصمم ومطور واجهات ويب محترف مقيم في العالم الرقمي. لأكثر من 5 سنوات، كرست شغفي لتحويل الأفكار الإبداعية إلى واجهات تفاعلية مذهلة وتجارب مستخدم لا تُنسى. أجمع بين اللمسة الفنية الأنيقة والمهارة التقنية العالية لتقديم حلول متكاملة تضمن تفوق عملائي.",
  aboutTextEn: "I am Malek, professional UI/UX Designer & Frontend Developer, known digitally as Malek Logic. For over 5 years, I've committed my energy to transforming challenging concepts into pixel-perfect interfaces and immersive interactive systems. I bridge visual elegance with modern code standards to yield products that standout.",
  heroTextAr: "أصنع تجارب رقمية إبداعية تروي قصتك",
  heroTextEn: "Designing Digital Experiences That Tell Your Story",
  heroSubAr: "دمج احترافي بين الإبداع البصري القائم على الـ Glassmorphism والتطوير البرمجي الفائق لصنع واجهات رقمية مذهلة وقابلة للتوسع.",
  heroSubEn: "Fusing beautiful Glassmorphism design and micro-animations with ultra-fast frontend engineering to craft interfaces that inspire and scale.",
  profileImg: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop",
  logoImg: "",
  heroBgImg: "",
  nameAr: "المهندس مالك لوجيك",
  nameEn: "Malek Ahmed",
  professionAr: "مصمم ومطور تفاعلي",
  professionEn: "UI/UX & Web Dev Artist",
  logoTextAr: "مالك لوجيك",
  logoTextEn: "MALEK LOGIC",
  fontFamily: "thmanyah-sans",
  customFontFamily: "",
  customFontUrl: "",
  accentColor: "#EA580C",
  socialFacebook: "https://facebook.com/malekart",
  socialTwitter: "https://twitter.com/malekart",
  socialLinkedin: "https://linkedin.com/in/malekart",
  socialGithub: "https://github.com/malekart",
  socialInstagram: "https://instagram.com/malekart",
  socialLinks: [
    { id: 'soc-1', platform: 'GitHub', url: 'https://github.com/malekart' },
    { id: 'soc-2', platform: 'LinkedIn', url: 'https://linkedin.com/in/malekart' },
    { id: 'soc-3', platform: 'Twitter/X', url: 'https://twitter.com/malekart' },
    { id: 'soc-4', platform: 'Instagram', url: 'https://instagram.com/malekart' }
  ],
  stat1Value: "+50",
  stat1LabelAr: "مشروع مكتمل",
  stat1LabelEn: "Completed Projects",
  stat2Value: "+5",
  stat2LabelAr: "سنوات الخبرة الإبداعية",
  stat2LabelEn: "Years of Experience",
  stat3Value: "100%",
  stat3LabelAr: "رضا العملاء والشغف",
  stat3LabelEn: "Client Satisfaction",
  aiCustomPromptAr: "نظام مستشار التخطيط الذكي - نشط وجاهز للتحليل الفوري باحترافية كاملة.",
  aiCustomPromptEn: "Intelligent Project Advisor - Active, responsive, and ready for modern product layouts.",
  resumePhone: "+966 50 000 0000",
  resumeEmail: "malikalwesabi@gmail.com",
  resumeLocation: "الرياض، المملكة العربية السعودية / Riyadh, KSA",
  resumeSummaryAr: "مصمم ومطور تفاعلي شغوف، ذو خبرة تفوق الخمس سنوات في تحويل الأفكار الإبداعية إلى منتجات رقمية فريدة تدمج بين جمال التصميم وقوة الأداء التقني واستهداف تجارب مستخدم حرة.",
  resumeSummaryEn: "Highly passionate UI/UX Designer & Web Developer with 5+ years of active experience bringing creative visual ideas to life through robust frontend architectures and sleek design specs.",
  resumeExperienceAr: "• مصمم واجهات رائد - استوديو مالك لوجيك الرياض (2023 - الآن): قيادة تصميم واجهات المستخدم لأكثر من 30 تطبيقاً رقمياً استثنائياً وتصميم أنظمة تصميم موحدة.\n• مطور واجهات ويب - منصات إبداعية رقمية (2021 - 2023): بناء وتطوير منصات ويب متجاوبة وتفاعلية لعملاء في الشرق الأوسط باستخدام React وTailwind.\n• مصمم مستقل ومستشار للشركات الناشئة والمصانع الرقمية (2019 - 2021)",
  resumeExperienceEn: "• Lead UI/UX Designer - Malek Logic Studio Riyadh (2023 - Present): Leading design files for 30+ innovative software solutions and configuring highly interactive design systems.\n• Frontend Engineer - Creative Digital Platforms (2021 - 2023): Developing lightweight responsive web apps using modern React, Tailwind, and high-DPI assets.\n• Freelance Interaction Designer & Startup Consultant (2019 - 2021)",
  resumeEducationAr: "• بكالوريوس في علوم الحاسوب وتقنيات الويب\n• شهادة متخصصة معتمدة في هندسة تجربة المستخدم وتفاعل الإنسان مع الحاسوب",
  resumeEducationEn: "• Bachelor's Degree in Computer Science & Web Technologies\n• Advanced Professional Certification in UX Architecture & Human-Computer Interaction"
};

export const TRANSLATIONS = {
  ar: {
    navHome: "الرئيسية",
    navAbout: "من أنا",
    navServices: "الخدمات",
    navPortfolio: "ملف الأعمال",
    navMatchmaker: "مستشار الذكاء الاصطناعي",
    navContact: "تواصل معي",
    navAdmin: "لوحة التحكم",
    navAdminExit: "خروج من الإدارة",
    
    heroTitlePrefix: "مرحباً في عالم",
    heroTitleName: "مالك لوجيك | Malek Logic",
    heroAccentTitle: "مصمم ومطور واجهات ويب",
    heroCtaWork: "شاهد أعمالي",
    heroCtaContact: "تواصل مباشر",
    
    statsSecTitle: "نجاح بالأرقام",
    
    aboutSecTitle: "من أكون؟",
    aboutSubtitle: "قصص نجاح نرويها بالإبداع والتفوق التقني",
    aboutYears: "سنوات خبرة متواصلة",
    aboutSkillsTitle: "ترسانة المهارات الإبداعية",
    downloadCv: "تحميل السيرة الذاتية",
    
    servicesSecTitle: "الخدمات الإبداعية",
    servicesSubtitle: "كيف يمكنني مساعدة مشروعك على الريادة الرقمية؟",
    
    portfolioSecTitle: "معرض المشاريع",
    portfolioSubtitle: "باقة من أحدث أعمالنا الإبداعية في التصميم والتطوير",
    filterAll: "سائر الأعمال",
    viewProject: "تفاصيل العمل",
    visitLive: "زيارت الموقع",
    projectCategory: "التصنيف:",
    projectDate: "التاريخ:",
    closeBtn: "إغلاق",
    
    aiSecTitle: "مستشار التخطيط الذكي (AI)",
    aiSubtitle: "اكتب فكرة مشروعك، وسيقوم الذكاء الاصطناعي بتحليلها واقتراح كيفية تنفيذه مع عرض المشاريع المشابهة لك من أعمال مالك",
    aiPlaceholder: "مثال: أريد إنشاء تطبيق لإدارة المطاعم بواجهات فاخرة وتصميم داكن وحركات أنيقة...",
    aiBudgetText: "مستوى الميزانية التقريبي:",
    aiBudgetLow: "محدودة (أقل من $2000)",
    aiBudgetMid: "متوسطة ($2000 - $5000)",
    aiBudgetHigh: "متقدمة (أكثر من $5000)",
    aiSubmitBtn: "تحليل وتوصيف المشروع بالذكاء الاصطناعي",
    aiAnalyzing: "جاري اتصال ذكي بالنموذج وجدولة التقرير...",
    aiError: "حدث خطأ أثناء إجراء التحليل الذكي. يرجى المحاولة لاحقاً.",
    aiMatchesHeader: "المشاريع الملهمة المشابهة من أعمالي:",
    aiApproachHeader: "خطة مالك المقترحة لتنفيذ مشروعك:",
    aiNoInput: "الرجاء كتابة فكرة مشروعك للحصول على الاستشارة الفورية.",
    
    contactSecTitle: "لنصنع عملاً استثنائياً معاً",
    contactSubtitle: "هل لديك فكرة مشروع أو ترغب باستشارة مجانية؟ بادر بالتواصل وسأرد عليك خلال 24 ساعة.",
    contactName: "الاسم الكريم",
    contactEmail: "بريدك الإلكتروني",
    contactSubject: "موضوع الرسالة",
    contactSubjectUi: "طلب تصميم واجهات UI/UX",
    contactSubjectDev: "تطوير موقع أو تطبيق ويب",
    contactSubjectBranding: "بناء هوية بصرية بالكامل",
    contactSubjectConsult: "استشارة رقمية وتقنية",
    contactSubjectOther: "أمر آخر",
    contactMessage: "تفاصيل رسالتك أو فكرتك",
    contactSubmitBtn: "إرسال رسالتك الآن",
    contactSending: "جاري إرسال الرسالة السلكية...",
    contactSuccess: "شكراً لتواصلك الفاخر! تم استلام رسالتك بنجاح وسأقوم بالتواصل معك في أقرب فرصة.",
    contactError: "حدث خطأ ما، يرجى ملء الحقول المطلوبة والتأكد من بريدك الإلكتروني.",
    socialLinksTitle: "تابعنا على وسائل التواصل الاجتماعي",
    
    adminLoginTitle: "بوابة التحكم الآمنة",
    adminPasswordLabel: "كلمة مرور المدير",
    adminLoginBtn: "دخول آمن",
    adminIncorrect: "كلمة المرور غير صحيحة، يرجى المحاولة مجدداً.",
    adminWelcome: "مرحباً مالك! لوحة إدارة المحتوى الاحترافية (CMS)",
    adminTabProjects: "إدارة المشاريع",
    adminTabServices: "إدارة الخدمات",
    adminTabContent: "تعديل النصوص",
    adminTabMessages: "رسائل العملاء",
    
    adminAddProject: "إضافة مشروع جديد",
    adminEditProject: "تعديل المشروع",
    adminDeleteConfirm: "هل أنت متأكد من حذف هذا المشروع؟",
    adminSave: "حفظ التغييرات",
    adminCancel: "إلغاء الإجراء",
    
    adminProjTitleAr: "العنوان بالعربية",
    adminProjTitleEn: "العنوان بالإنجليزية",
    adminProjDescAr: "الوصف المختصر بالعربية",
    adminProjDescEn: "الوصف المختصر بالإنجليزية",
    adminProjContAr: "التفاصيل الطويلة بالعربية",
    adminProjContEn: "التفاصيل الطويلة بالإنجليزية",
    adminProjImage: "رابط صورة المعاينة (URL)",
    adminProjCatAr: "التصنيف بالعربية",
    adminProjCatEn: "التصنيف بالإنجليزية",
    adminProjLink: "رابط مباشر للموقع (اختياري)",
    adminProjDate: "تاريخ المشروع (مثال: 2026-06)",
    adminProjOrder: "الرقم الترتيبي للظهور",
    
    adminServTitleAr: "اسم الخدمة بالعربية",
    adminServTitleEn: "اسم الخدمة بالإنجليزية",
    adminServDescAr: "الوصف بالعربية",
    adminServDescEn: "الوصف بالإنجليزية",
    adminServIcon: "اسم الأيقونة من Lucide",
    
    adminContHeroAr: "العنوان الرئيسي المفتتح بالعربية",
    adminContHeroEn: "العنوان الرئيسي المفتتح بالإنجليزية",
    adminContHeroSubAr: "الوصف الفرعي بالبطل بالعربية",
    adminContHeroSubEn: "الوصف الفرعي بالبطل بالإنجليزية",
    adminContAboutAr: "نبذة عني بالعربية",
    adminContAboutEn: "نبذة عني بالإنجليزية",
    adminContProfile: "رابط الصورة الشخصية",
    adminContSaveSuccess: "تم حفظ نصوص الموقع بنجاح!",
    
    adminNoMessages: "لا توجد رسائل عملاء واردة حتى الآن.",
    adminMsgFrom: "المرسل:",
    adminMsgSubject: "الموضوع:",
    adminMsgDate: "تاريخ الاستلام:",
    adminDeleteMsg: "حذف الرسالة",
    
    footerRights: "جميع الحقوق محفوظة. تم تصميمه بكل شغف وإبداع بواسطة مالك لوجيك © 2026",
    footerRightsEn: "All Rights Reserved. Handcrafted with passion & code by Malek Logic © 2026"
  },
  en: {
    navHome: "Home",
    navAbout: "About Me",
    navServices: "Services",
    navPortfolio: "Portfolio",
    navMatchmaker: "AI Consultation",
    navContact: "Contact",
    navAdmin: "CMS Panel",
    navAdminExit: "Exit CMS",
    
    heroTitlePrefix: "Welcome to the world of",
    heroTitleName: "Malek Logic",
    heroAccentTitle: "UI/UX Designer & Web Developer",
    heroCtaWork: "View Portfolio",
    heroCtaContact: "Get in Touch",
    
    statsSecTitle: "Success in Numbers",
    
    aboutSecTitle: "Who Is Malek?",
    aboutSubtitle: "Fusing Design Aesthetics with Pure Engineering Craft",
    aboutYears: "Years Active Experience",
    aboutSkillsTitle: "Creative Skill Armory",
    downloadCv: "Download Resume",
    
    servicesSecTitle: "My Services",
    servicesSubtitle: "Elevating your brand visual and digital business capabilities",
    
    portfolioSecTitle: "Selected Projects",
    portfolioSubtitle: "A curated workspace exhibiting stellar frontend apps and interface systems",
    filterAll: "All Works",
    viewProject: "Project Details",
    visitLive: "Visit Website",
    projectCategory: "Category:",
    projectDate: "Date:",
    closeBtn: "Close",
    
    aiSecTitle: "Intelligent Project Advisor (AI)",
    aiSubtitle: "Submit your core business concept. Our custom AI will suggest execution guidelines, modern technical stacks, and map it directly to related works of Malek.",
    aiPlaceholder: "Example: I want a sleek dashboard for real-estate listing that uses futuristic dark UI, smooth glass transitions, and works blazing fast...",
    aiBudgetText: "Estimated Project Budget:",
    aiBudgetLow: "Entry-Level (Under $2000)",
    aiBudgetMid: "Growth ($2000 - $5000)",
    aiBudgetHigh: "Enterprise (Above $5000)",
    aiSubmitBtn: "Analyze Project with Gemini Intelligence",
    aiAnalyzing: "Contacting server-side model nodes & compiling index...",
    aiError: "An issue occurred connecting to the assistant nodes. Please inspect your config or try again.",
    aiMatchesHeader: "Similar Inspiring Works from My Portfolio:",
    aiApproachHeader: "Malek's Recommended Strategy & Stack:",
    aiNoInput: "Please write down your product idea to start AI consultation mapping.",
    
    contactSecTitle: "Let's Craft Something Stellar",
    contactSubtitle: "Possess an inspiring idea or need structured technical consultation? Message me and let's get rolling immediately.",
    contactName: "Your Full Name",
    contactEmail: "Email Address",
    contactSubject: "Message Subject",
    contactSubjectUi: "UI/UX Interface Design",
    contactSubjectDev: "Web Development Request",
    contactSubjectBranding: "Brand Identity Architecture",
    contactSubjectConsult: "Digital Audit & Consulting",
    contactSubjectOther: "Other Topic",
    contactMessage: "Tell me about your vision/project context",
    contactSubmitBtn: "Deploy Message Into Orbit",
    contactSending: "Broadcasting message across arrays...",
    contactSuccess: "Message acquired successfully! I will reach out to you within the next 24 hours.",
    contactError: "Please fulfill all required fields and confirm your email format.",
    socialLinksTitle: "Follow Us on Social Media",
    
    adminLoginTitle: "Protected Administrator Tunnel",
    adminPasswordLabel: "Vault Password",
    adminLoginBtn: "Establish Session",
    adminIncorrect: "Incorrect credentials. Secure lockout parameters active.",
    adminWelcome: "Welcome back, Malek. Digital Content Management Suite",
    adminTabProjects: "Projects Catalog",
    adminTabServices: "Services List",
    adminTabContent: "Main Content Sheets",
    adminTabMessages: "Inbox Submissions",
    
    adminAddProject: "Add Project Node",
    adminEditProject: "Update Project Node",
    adminDeleteConfirm: "Are you absolutely state-resolved to delete this project?",
    adminSave: "Commit Updates",
    adminCancel: "Suspend Workflow",
    
    adminProjTitleAr: "Title (Arabic)",
    adminProjTitleEn: "Title (English)",
    adminProjDescAr: "Brief Description (Arabic)",
    adminProjDescEn: "Brief Description (English)",
    adminProjContAr: "Deep Overview Description (Arabic)",
    adminProjContEn: "Deep Overview Description (English)",
    adminProjImage: "Showcase Image Path/URL",
    adminProjCatAr: "Category (Arabic)",
    adminProjCatEn: "Category (English)",
    adminProjLink: "Demo Address Link (Optional)",
    adminProjDate: "Date Node (Format: YYYY-MM)",
    adminProjOrder: "Index Placement Weight",
    
    adminServTitleAr: "Service Label (Arabic)",
    adminServTitleEn: "Service Label (English)",
    adminServDescAr: "Brief Description (Arabic)",
    adminServDescEn: "Brief Description (English)",
    adminServIcon: "Lucide Icon Key Name",
    
    adminContHeroAr: "Main Hero Broadcaster (Arabic)",
    adminContHeroEn: "Main Hero Broadcaster (English)",
    adminContHeroSubAr: "Hero Paragraph Support (Arabic)",
    adminContHeroSubEn: "Hero Paragraph Support (English)",
    adminContAboutAr: "About Malek Block (Arabic)",
    adminContAboutEn: "About Malek Block (English)",
    adminContProfile: "Portrait Image URL Link",
    adminContSaveSuccess: "Content segments saved into local memory successfully!",
    
    adminNoMessages: "No customer queries populated so far.",
    adminMsgFrom: "Originator:",
    adminMsgSubject: "Topic:",
    adminMsgDate: "Composed At:",
    adminDeleteMsg: "Purge Node",
    
    footerRights: "All Rights Reserved. Handcrafted with passion & code by Malek Logic © 2026",
    footerRightsEn: "All Rights Reserved. Handcrafted with passion & code by Malek Logic © 2026"
  }
};
